#!/bin/sh
# -*- mode: sh -*-

# set -x


RBENV_ORGA="${RBENV_ORGA:-https://github.com/rbenv}"
RBENV_REPO="${RBENV_REPO:-rbenv}"
RBENV_PLUGINS="${RBENV_PLUGINS:-ruby-build rbenv-vars}"
RBENV_PLUGINS_DEFAULT="${RBENV_PLUGINS:-ruby-build rbenv-vars}"


wrbenv_help()
{
    cat <<EOF
Usage is :
      $0 [-h] [-D] <action> <action_parameters>

with action in :
     list
     install
     update
EOF
}

rbenv_root()
{
    rbenv_root="${1:-$rbenv_root}"
    rbenv_root="${rbenv_root:-$RBENV_ROOT}"
    if [ -n "$HOME_ALT" ]; then
        rbenv_root="${rbenv_root:-$HOME_ALT/.rbenv}"
    fi
    rbenv_root="${rbenv_root:-$HOME/.rbenv}"
}

wrbenv_info()
{
    :
}

wrbenv_install()
{
    :
}

wrbenv_update()
{
    :
}

wrbenv()
{
    wrbenv=
    wrbenv__action=
    while getopts :hD opt; do
        case $opt in
            h) wrbenv_help
               exit 0
               ;;
            D) set -x ;;
        esac
    done
    shift $(($OPTIND - 1))

    case $1 in
        info|install|update|help|"")
            wrbenv__action="wrbenv_${1:-info}"
            [ $# -gt 1 ] && shift
            $wrbenv__action "$@"
            ;;
        *)
            echo >&2 "unknown action \"$1\""
            wrbenv_help
            exit 1
            ;;
    esac
}

case "$0" in
    */wrbenv)
        wrbenv "$@"
        ;;
esac
